version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 443:443
    volumes:
      - './nginx/fullchain.pem:/cert/fullchain.pem'
      - './nginx/privkey.pem:/cert/privkey.pem'

